port: 2008
secret: "your_repository_secret"
path: /home/ronaldzav/my_repo
private: true
tree: main

# Required for private repositories
account: 
  user: ronaldzav
  token: your_token

event:
  enable: true
  type: custom-command
  command: service your_service_name restart
  finish_command: yarn
